version: 1
# see https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html
# only this way I was able to get nextjs working in the new monorepo setup. Also needed to set AMPLIFY_MONOREPO_APP_ROOT to the same value as appRoot, since I already had the app deployed in non-monorepo style before.
applications:
  - appRoot: app
    frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - echo "Building frontend"
            - pwd
            # running from ./app
            # enable server-side env vars. see https://docs.aws.amazon.com/amplify/latest/userguide/ssr-environment-variables.html
            - env | grep -e NEXTAUTH_URL -e NEXTAUTH_SECRET -e BACKEND_BASE_URL -e MY_FIRST_NAME -e MY_AWS_USER_ACCESS_KEY_ID -e MY_AWS_USER_ACCESS_KEY_SECRET -e MY_AWS_DYNAMODB_TABLE_NAME -e MY_AWS_REGION -e MY_AWS_COGNITO_CLIENT_ID -e MY_AWS_COGNITO_CLIENT_SECRET -e MY_AWS_COGNITO_ISSUER >> .env.production
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - "**/*"
      cache:
        paths:
          - node_modules/**/*
